sudo: required
services:
  - docker

before_install:
  - docker build -t longbuibao/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true longbuibao/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-858201713588"
  bucket_path: "docker-react"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
